"""phase 1 ingest tables: companies, ipos, documents, prices

Revision ID: 70639db84014
Revises: 
Create Date: 2026-10-04 19:23:43.065812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70639db84014'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('nse_symbol', sa.String(length=32), nullable=True),
    sa.Column('bse_code', sa.String(length=16), nullable=True),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nse_symbol')
    )
    op.create_table('prices',
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('close', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'date')
    )
    op.create_table('ipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('open_date', sa.Date(), nullable=True),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('issue_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('issue_size_cr', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('fresh_cr', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('ofs_cr', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('exchange', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'open_date', name='uq_ipos_company_open')
    )
    op.create_index(op.f('ix_ipos_company_id'), 'ipos', ['company_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipo_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=8), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('n_pages', sa.Integer(), nullable=True),
    sa.Column('filed_on', sa.Date(), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['ipo_id'], ['ipos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ipo_id', 'doc_type', name='uq_documents_ipo_type')
    )
    op.create_index(op.f('ix_documents_ipo_id'), 'documents', ['ipo_id'], unique=False)
    op.create_index(op.f('ix_documents_sha256'), 'documents', ['sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_sha256'), table_name='documents')
    op.drop_index(op.f('ix_documents_ipo_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_ipos_company_id'), table_name='ipos')
    op.drop_table('ipos')
    op.drop_table('prices')
    op.drop_table('companies')
    # ### end Alembic commands ###
